---
title: "Seat Prediction"
output: html_document
---

```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(echo = TRUE)
source("import.R")
source("seat_projection.R")
```

```{r config}
last_election <- "F2008"
#last_election <- "F2011"
first_election <- "F1990"
parties <- c("Liberal", "Conservative", "Green", "New Democratic", "Bloc Québécois")

#popular_votes <- c(39.47, 31.91, 3.43, 19.73, 4.67)
#popular_votes <- c(36, 38, 4, 15, 6)
#popular_votes <- c(41, 31, 5, 18, 5)
popular_votes <- c(18.91, 39.62, 3.91, 30.63, 6.04)
#popular_votes <- c(30, 30, 5, 30, 5)
polling <- data.table(party_name=parties, popular_vote_percent=popular_votes)

# lm, uniform, proportional
swing_mode <- "lm"

kable(polling)
qplot(party_name, popular_vote_percent, data=polling[order(-popular_vote_percent)], fill=party_name, geom="col") + coord_flip() + scale_party_fills
```

```{r calc}

data <- PECRE[
  first_election <= election_id & election_id <= last_election & party_name %in% parties,]
recent <- data[election_id == last_election,
  .(riding_id, party_name, votes_percent, popular_vote_percent, candidate_name, order)]

models <- seat_projection_model(data=data, recent=recent, mode=swing_mode)
res0 <- project_seats(models=models, polling=polling)

models <- res0$models
winners <- res0$winners
seats <- res0$seats
changes <- res0$get_changes()
```

```{r}
#qplot(party_name, votes_percent, data=models, fill=party_name, geom="col") + facet_grid(riding_id ~ .) + scale_party_fills


#summary(models)
kable(models)

kable(winners[predicted_order!=order][order(party_name)])

kable(changes[prev_winner!=new_winner,][order(prev_winner)])

seats <- seats[
  PE[
    election_id == last_election & party_name %in% parties,
   .(party_name,old_seats=seats_elected,old_pv=popular_vote_percent)
  ],
  on="party_name"]
kable(seats)

qplot(party_name, seat_projection, data=seats[order(-seat_projection)], fill=party_name, geom="col") + coord_flip() + scale_party_fills
```

# Repeated Simulations
```{r repeats}
deviation <- 3
runs <- 10000L

Runs <- data.table(deviate(polling$popular_vote_percent, sd=deviation, n=runs), run=1L:runs)

res <- Runs[
  ,polling[,.(party_name, popular_vote_percent=c(V1, V2, V3, V4, V5))],
  by="run"
][, {
  d1 <- project_seats(models, .SD)$seats
  g <- gallagher(d1)
  d1[,`:=`(gallagher_index = g$gi, sli = g$sli)]
  d1
}, by="run"]

qplot(popular_vote_percent, data=res, col=party_name, fill=party_name, bins=100) + scale_party_colours + scale_party_fills + scale_x_continuous(breaks=seq(0,100,5), minor_breaks = seq(0,100,1)) + facet_grid(party_name ~ ., scales="free_y")

total_seats <- res[,.(total_seats=sum(seat_projection)),by="run"][1]$total_seats

qplot(seat_projection, data=res, col=party_name, fill=party_name, bins=100) +
  scale_party_colours + scale_party_fills +
  scale_x_continuous(
    breaks = as.integer(seq(0,total_seats, total_seats/4)),
    minor_breaks=seq(0, total_seats, total_seats/32)) +
  facet_grid(party_name ~ ., scales="free_y")

kable(res[,.(min=min(seat_projection), avg=round(mean(seat_projection)), mid=median(seat_projection), max=max(seat_projection)), by="party_name"])
kable(res[,.(min=min(popular_vote_percent), avg=mean(popular_vote_percent), mid=median(popular_vote_percent), max=max(popular_vote_percent)), by="party_name"])

winner_stats <- res[
  , {
    top <- .SD[order(-seat_projection)][1]
    .(winner=top$party_name, seats=top$seat_projection, is_majority = top$seat_projection >= total_seats/2)
  }, by="run"][, .(count=.N), by=c("winner", "is_majority")]

kable(winner_stats[, prob := 100 * count / sum(count)])
setorder(winner_stats, -prob, winner, is_majority)

winner_stats_1 <- winner_stats[,.(count=sum(count), prob=sum(prob)), by="winner"]
setorder(winner_stats_1, -prob, winner)

kable(winner_stats_1)
kable(winner_stats)

qplot(gallagher_index, sli, data=res, alpha=I(0.05))
```

# Vote Shift Analysis

```{r shift}
func <- function(party, vec) {
  data.table(mode=c("lm", "uniform", "proportional"))[,{
    models <- seat_projection_model(data=data, recent=recent, mode=mode)
    data.table(k=seq(-100, 130, 0.25))[,{
      d1 <- project_seats(
        models, 
        data.table(
          party_name=polling$party_name,
          popular_vote_percent=
            normalize_percents(clamp_percents(polling$popular_vote_percent + k*vec/5))
        )
      )$seats
      g <- gallagher(d1)
      d1[, `:=`(gallagher_index = g$gi, sli = g$sli, mode=mode)]
      d1
    }, by="k"][party_name==party]
  }, by="mode"]
}

LIBx <- func("Liberal", c(5,-1,-1,-1,-1))
CONx <- func("Conservative", c(-1,5,-1,-1,-1))
GRNx <- func("Green", c(-1,-1,5,-1,-1))
NDPx <- func("New Democratic", c(-1,-1,-1,5,-1))
BQx <- func("Bloc Québécois", c(-1,-1,-1,-1,5))

x <- rbind(LIBx,CONx,GRNx,NDPx,BQx)
qplot(popular_vote_percent, seat_projection, data=x, col=party_name, geom="line", facets = mode ~ .) +
  scale_party_colours +
  geom_line(aes(x,y), data=data.table(x=c(0,100), y=c(0, total_seats)), col="white", alpha=0.5) +
  scale_x_continuous(breaks=seq(0,100,5), minor_breaks=seq(0,100,1), limits=c(0,100)) +
  scale_y_continuous(breaks=seq(0,total_seats,20), minor_breaks=seq(0,total_seats,10), limits=c(0, total_seats))
```

# Swing Analysis

```{r swings}
simulate_swing <- function(vec, ks) {
  DT <- NA
  models <- seat_projection_model(data=data, recent=recent, mode="lm")
  pvs <- PE[election_id==last_election & party_name %in% parties][
    ,.(party_name, popular_vote_percent=popular_vote_percent)][match(parties, party_name)]
  for (k in ks) {
    res <- project_seats(
      models, 
      data.table(
        party_name=polling$party_name,
        popular_vote_percent=
          normalize_percents(clamp_percents(pvs$popular_vote_percent + k*vec))
      )
    )
    changes <- res$get_changes()
    changes1 <- copy(changes)[, k := k]
    setorder(changes1, riding_id)
    if (!is.data.table(DT))
      DT <- changes1
    else
      DT <- rbind(DT, changes1)
  }
  DT
}

ss <- simulate_swing(c(1,-1,0,0,0), -10L:10L)
setorder(ss, riding_id)
kable(ss[k != 0])
```